# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConsoleGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Console(object):
    def setupUi(self, Console):
        Console.setObjectName("Console")
        Console.setWindowModality(QtCore.Qt.NonModal)
        Console.resize(1431, 901)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/CalibrationImages/resource/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Console.setWindowIcon(icon)
        Console.setAutoFillBackground(False)
        Console.setModal(False)
        self.ConsoleOutput = QtWidgets.QTextBrowser(Console)
        self.ConsoleOutput.setEnabled(True)
        self.ConsoleOutput.setGeometry(QtCore.QRect(30, 30, 1371, 841))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ConsoleOutput.setFont(font)
        self.ConsoleOutput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ConsoleOutput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ConsoleOutput.setLineWidth(1)
        self.ConsoleOutput.setObjectName("ConsoleOutput")

        self.retranslateUi(Console)
        QtCore.QMetaObject.connectSlotsByName(Console)

    def retranslateUi(self, Console):
        _translate = QtCore.QCoreApplication.translate
        Console.setWindowTitle(_translate("Console", "Stella CapTouch Test System - Console Output"))
import CapTouch_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Console = QtWidgets.QDialog()
    ui = Ui_Console()
    ui.setupUi(Console)
    Console.show()
    sys.exit(app.exec_())
